apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tomcat-de
  namespace: default
  labels:
    app: tomcat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - image: tomcat
        imagePullPolicy: IfNotPresent
        name: tomcat
