---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: metadatas.doslab.io
spec:
  additionalPrinterColumns:
  - JSONPath: .type
    name: type
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: created
    type: string
  group: doslab.io
  names:
    kind: Metadata
    plural: metadatas
    singular: metadata
  scope: Namespaced
  version: v1
